# Generated by Django 4.2.8 on 2025-03-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_userdata_client_group_exercise_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcategory',
            name='created_by',
        ),
    ]
