# Generated by Django 4.2.8 on 2025-03-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_exercise_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselanguage',
            old_name='language_name',
            new_name='name',
        ),
    ]
