# Generated by Django 4.2.8 on 2025-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_workout_workoutexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
